### ISSUE TITLE
Downloaded Layer do not persist when saving project

### ISSUE THREAD

**Issue by patricknoack** [geocledian/agknow_qgis3#6]
Raster data downloaded from the server during a QGIS session does not persist in the project after saving. The files need to be reloaded every time the project is opened. All changes made (e.g. style assignment) are lost.

It would be very helpful to be able to provide a folder name where the data is stored permanently.

**Comment by gc-sommer** [comment]
Hi Patrick!

Now you have the option to export the images to a folder of your choice and the paths to the rasters are also updated then in the TOC.

Best regards,
Johannes
